variables:
  GITHUB_MIRROR_URL: "/hamolicious/neovim-configuration.git"

include:
  - project: "gitlab/default-pipelines"
    file: "/gitlab-ci/mirror.gitlab-ci.yml"

mirror_to_github:
  stage: deploy
  needs: []
  when: always
